# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f637ed946eccc3c3e31cdfc0f37f25ee7f831c144616b6ee357ea7cd320431e7ae01ffd43efcceb4d0ee9037f2cf8055253845f0165e8f13a1b3c7cfe8be2971

test:
  secret_key_base: ca0533b67a4f467c485ce43d4bde433dcb31087f83582b216ee6da0456e3c7fb5f8a0ab98bff8bcde227f976b6b466845cfc4d77c0c1d93cf1a3bf16679d5b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
